---
Formação Cientista de Dados 
Amostragem Simples

1 - Amostra simples de 150 de 0 e 1 + replace TRUE + Prob igual -
2 - Amostra simples de 150 de 0 e 1 + replace TRUE + Prob Diferentes
3 - Amostra simples de 150 de 0 a 1000 + replace FALSE 
4 - Gerando amostra de conjuntos de dados 30% iris ( com base na amostra 2)
5 - Repetir experimento com mesmo resultado ( por meio de semente set.seed(n))

---
150 amostras, de zero e 1, com reposição, prob. equivalentes
```{r}
amostra = sample(c(0,1), 150, replace = TRUE, prob=c(0.5,0.5))
amostra
summary(as.factor(amostra))
```
150 amostras, de zero e 1, com reposição, mais chances para zero
```{r}
amostra = sample(c(0,1), 150, replace = TRUE, prob=c(0.7,0.3))
amostra
summary(as.factor(amostra))
```
150 amostras, de 1 a 1000, sem reposição, prob. equivalentes
```{r}
amostra = sample(c(1:1000), 150, replace = FALSE)
amostra
```
Gerado amostra de conjuntos de dados
30% dos dados de iris
```{r}
amostra = sample(c(0,1), 150, replace = TRUE, prob=c(0.7,0.3))
summary(as.factor(amostra))
```
Gera a amostra
```{r}
amostrairis = iris[amostra==1,]
amostrairis
dim(amostrairis)
```
Repetir experimento
```{r}
set.seed(2345)
sample(c(1000), 1)
```
Repetindo
```{r}
set.seed(2345)
sample(c(1000), 1)
```
