---
Formação Cientista de Dados - Prof. Fernando Amaral
Teorema Central do Limite

(Instalação do package semtools)
1 - Criação de uma variável vetor
2 - Cria um loop "for" que irá iterar 500 vezes.
Dentro do loop, cria uma amostra aleatória multivariada não-normais com 1000 observações, utilizando a função "mvrnonnorm()" do pacote "MVN" em R. 
Essa amostra tem duas variáveis, com médias de 1 e 2, respectivamente, e uma matriz de covariância personalizada.
Calcula a média da amostra criada e armazena o valor em um vetor "z".
Se o índice da iteração do loop for menor que 4, cria um histograma das duas variáveis da amostra utilizando a função "hist()" do R.
3 - Imprime a distribuição da média das amostras
---
Teorema Central do Limite
```{r}
#omitir warnings
options(warn=-1)
install.packages("semTools")
library(semTools)

```
Inicializa um vetor 
```{r}
z = rep(0,500)
```
Gera as amostras
```{r}
for (i in 1:500) {
  m = mvrnonnorm(1000, c(1, 2), matrix(c(10, 2, 2, 5), 2, 2),
                 skewness = c(5, 2), kurtosis = c(3, 3))
  #grava a média da amostra
  z[i] =mean(m)
  
  #imprime as 3 primeiras
  if (i<4){
   
    hist(m,breaks=50, main= paste0("Histrograma ", i ))
  }
}
```
Imprime a distribuição da média das amostras
```{r}
hist(z)
```

